exports.getAllEmployeeAttributes = () => {
    return {
        company: 1,
        empCode: 1,
        empFullName: 1,
        empDOB: 1,
        empDesignation: 1,
        empJoiningDate: 1,
        empReportTo: 1,
        empCadre: 1,
        empContactNo: 1,
        empAadharNo: 1,
        empPANNo: 1,
        empGender: 1,
        empEmailCompany: 1,
        empEmailPersonal1: 1,
        empEmailPersonal2: 1,
        empFatherFullName: 1,
        empMotherFullName: 1,
        empSpouseFullName: 1,
        empJoiningLocation: 1,
        empGrade: 1,
        empDesignation: 1,
        empDepartment: 1,
        empCadre: 1,
        empDOBS: 1,
        empJoiningDateS: 1,
        empStatus: 1,
        createdAt: 1
    };
};
exports.getAllEmployeeExcelAttributes = () => {
    return {
        empFirstName: 1,
        empMiddleName: 1,
        empLastName: 1,
        empFullName: 1,
        empGender: 1,
        // empDOB: {$dateToString: {format: "%d-%m-%Y", date: "$empDOB"}},
        empDOB: {$dateToString: {format: "%d-%m-%Y", date: new Date("$empDOB")}},

        empContactNo: 1,
        empAadharNo: 1,
        empPANNo: 1,
        empMartialStatus: 1,
        qualification: 1,
        empPFNo: 1,
        empESICNo: 1,
        empEmailCompany: 1,
        empEmailPersonal1: 1,
        empEmailPersonal2: 1,
        empFatherFullName: 1,
        // empFatherDOB: {$dateToString: {format: "%d-%m-%Y", date: "$empFatherDOB"}},
        empFatherDOB: {$dateToString: {format: "%d-%m-%Y", date: new Date("$empFatherDOB")}},

        empFatherOccupation: 1,
        empMotherFullName: 1,
        // empMotherDOB: {$dateToString: {format: "%d-%m-%Y", date: "$empMotherDOB"}},
        empMotherDOB: {$dateToString: {format: "%d-%m-%Y", date: new Date("$empMotherDOB")}},

        empMotherOccupation: 1,
        empSpouseFullName: 1,
        // empSpouseDOB: {$dateToString: {format: "%d-%m-%Y", date: "$empSpouseDOB"}},
        empSpouseDOB: {$dateToString: {format: "%d-%m-%Y", date: new Date("$empSpouseDOB")}},

        empSpouseOccupation: 1,
        noOfDependentChildren: 1,
        fullNameOfDependentChild1: 1,
        fullNameOfDependentChild2: 1,
        // empJoiningDate: {$dateToString: {format: "%d-%m-%Y", date: "$empJoiningDate"}},
        empJoiningDate: {$dateToString: {format: "%d-%m-%Y", date: new Date("$empJoiningDate")}},
        empJoiningLocation: 1,
        empGrade: 1,
        empDesignation: 1,
        empDepartment: 1,
        empReportTo: "$empReportTo.empFullName",
        empOTApplicability: 1,
        empType: 1,
        empCadre: 1,
        empBefName: 1,
        empBankName: 1,
        empBankBranch: 1,
        empAccType: 1,
        empAccountNumber: 1,
        empBankIFSCCode: 1
    };
};
exports.getAllEmployeeExitReportAttributes = () => {
    return {
        company: 1,
        empCode: 1,
        empFullName: 1,
        empDesignation: 1,
        empJoiningDate: 1,
        empJoiningDateS: 1,
        empReportTo: 1,
        empCadre: 1,
        empDateOfResignation: 1,
        empStatus: 1,
        empGrade: 1,
        empDepartment: 1,
        reasonOfLeaving: 1,
        empDateOfResignationS: 1
    };
};
